name: timeline
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: filiph <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  angular: ^5.0.0-beta+1
  angular_components: ^0.9.0-beta
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.5.3
  intl: ^0.15.7
  rxdart: ^0.18.1
  sass_builder: ^2.1.1

dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.2
  built_value_generator: ^5.5.3
  build_web_compilers: ^0.4.0
